server :
    port : 9090

spring :
   datasource:
     username: root
     password: 2345678
     url : jdbc:mysql://localhost:3306/demobase?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
     driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.example.demo.entity
  mapper-locations: classpath:mapping/*Mapper.xml

#showSql
  level:
    com :
      example :
         mapper :debug
